on:
  workflow_dispatch:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Creating release

jobs:
  build_wheels:
    name: "[${{ strategy.job-index }}/${{ strategy.job-total }}] py${{ matrix.py }} on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest, macos-14]
        py: ["cp38"]

    steps:
      - uses: actions/checkout@v4

      - name: Setting up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Set up QEMU
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.22.0
        env:
          CIBW_BUILD: "${{ matrix.py }}-*"

      - uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.os }}-${{ matrix.py }}
          path: ./wheelhouse/*.whl

  upload_all:
    needs: [build_wheels]
    name: Creating Github release.
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Fetch all artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: dist-*
          merge-multiple: true

      - name: Display structure of downloaded files
        run: ls -R

      - name: Release with Notes
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: '*.whl'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
